feign:
  client:
    config:
      clientGiphy:
        errorDecoder: com.ab.app_for_a_b.client.error_decoder.GiphyFeignErrorDecoder
        loggerLevel: BASIC
        connectTimeout: 5000
        readTimeout: 5000
      clientExchangeRates:
        errorDecoder: com.ab.app_for_a_b.client.error_decoder.ExchangeRateFeignErrorDecoder
        loggerLevel: BASIC
        connectTimeout: 5000
        readTimeout: 5000

url:
  exchange_rates:
    main: 'https://openexchangerates.org/api/'
    last_prefix: 'historical/'
    latest_prefix: 'latest'
    base_params: '.json?app_id=78ee667e21694435a959959a947f6ee4&base=usd&symbols=rub'
  giphy:
    main: 'https://api.giphy.com/v1/gifs/random'
    api_id: '&api_key=0UTRbFtkMxAplrohufYco5IY74U8hOes'
    rich: '?tag=rich'
    broke: '?tag=broke'
